font pango:monospace, FontAwesome 8

smart_borders on
hide_edge_borders smart

include ~/.config/i3/themes/current/theme/i3.conf

for_window [class="pkg-installer"] floating enable, resize set 900 600, move position center
for_window [class="i3-floating-tui"] floating enable, resize set 900 600, move position center
for_window [instance="i3-floating-tui"] floating enable, resize set 900 600, move position center
for_window [title="^i3-floating-tui:"] floating enable, resize set 900 600, move position center
