mode "resize" {
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        bindsym Left  resize shrink width 10 px or 10 ppt
        bindsym Down  resize grow height 10 px or 10 ppt
        bindsym Up    resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

set $system System
mode "$system" {
    bindsym l exec ~/.config/i3/scripts/lock-screen, mode "default"
    bindsym e exec i3-msg exit, mode "default"
    bindsym s exec ~/.config/i3/scripts/lock-and-suspend, mode "default"
    bindsym r exec systemctl reboot, mode "default"
    bindsym q exec systemctl poweroff, mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+Escape mode "$system"

set $launch Launch
mode "$launch" {
    bindsym f exec firefox
    bindsym c exec code
    bindsym s exec spotify
    bindsym q exec qbittorrent
    bindsym t exec thunar

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+Shift+space mode "$launch"
